function colors = makeGroupColors(hue, n, S, Vmin, Vmax)
    % S = 0.75;                          % saturation
    V = linspace(Vmin, Vmax, n);        % light → dark
    colors = hsv2rgb([ ...
        hue*ones(n,1), ...
        S*ones(n,1), ...
        V' ]);
end